name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run the build command
      - name: Build project
        working-directory: ./packages/mui
        run: pnpm run build

      # Set version
      - name: Set canary version
        id: set-version
        working-directory: ./packages/mui
        run: |
          # Get the current version
          CURRENT_VERSION=$(pnpm version --json | jq -r '.["@usememos/mui"]')
          # Generate a canary version (e.g., 0.1.0-20231025120000)
          VERSION="${CURRENT_VERSION}-$(date +%Y%m%d%H%M%S)"
          # Set the new version
          pnpm version $VERSION --no-git-tag-version
          # Output the new version
          echo "New version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Publish the dist directory to npm
      - name: Publish to npm
        working-directory: ./packages/mui
        run: |
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
