name: Publish npm package with pnpm (beta)

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      # 3. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Navigate to the /packages/mui directory
      - name: Navigate to package directory
        run: cd packages/mui
        shell: bash

      # 5. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 6. Run the build command
      - name: Build project
        run: pnpm run build

      # 7. Set beta version
      - name: Set beta version
        id: set-version
        run: |
          # Get the current version
          CURRENT_VERSION=$(pnpm version --json | jq -r '.["packages/mui"].version')
          # Generate a beta version (e.g., 0.1.0-beta.20231025120000)
          BETA_VERSION="${CURRENT_VERSION}-beta.$(date +%Y%m%d%H%M%S)"
          # Set the new version
          pnpm version $BETA_VERSION --no-git-tag-version
          # Output the new version
          echo "New beta version: $BETA_VERSION"
          echo "beta_version=$BETA_VERSION" >> $GITHUB_OUTPUT

      # 8. Publish the dist directory to npm with the beta tag
      - name: Publish to npm (beta)
        run: |
          cd dist
          pnpm publish --tag beta --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}